const foodItems = [
  // Breakfast items
  {
    id: 1,
    name: "Pancakes",
    category: "Breakfast",
    detail: "Fluffy pancakes served with maple syrup and fresh berries.",
    price: 5.99,
    rating: 4.5,
    image: "https://via.placeholder.com/150?text=Pancakes",
  },
  {
    id: 2,
    name: "Omelette",
    category: "Breakfast",
    detail: "Three-egg omelette with cheese, tomatoes, and bell peppers.",
    price: 4.99,
    rating: 4.2,
    image: "https://via.placeholder.com/150?text=Omelette",
  },
  {
    id: 3,
    name: "French Toast",
    category: "Breakfast",
    detail:
      "Thick slices of bread dipped in egg batter and fried to perfection.",
    price: 6.99,
    rating: 4.7,
    image: "https://via.placeholder.com/150?text=French+Toast",
  },
  {
    id: 4,
    name: "Smoothie Bowl",
    category: "Breakfast",
    detail: "Blended fruit topped with granola, nuts, and honey.",
    price: 7.99,
    rating: 4.6,
    image: "https://via.placeholder.com/150?text=Smoothie+Bowl",
  },
  {
    id: 5,
    name: "Avocado Toast",
    category: "Breakfast",
    detail: "Toasted bread topped with mashed avocado, salt, and pepper.",
    price: 5.49,
    rating: 4.8,
    image: "https://via.placeholder.com/150?text=Avocado+Toast",
  },
  {
    id: 6,
    name: "Granola Parfait",
    category: "Breakfast",
    detail: "Layers of granola, yogurt, and fresh berries.",
    price: 6.49,
    rating: 4.4,
    image: "https://via.placeholder.com/150?text=Granola+Parfait",
  },

  // Lunch items
  {
    id: 7,
    name: "Caesar Salad",
    category: "Lunch",
    detail:
      "Romaine lettuce with Caesar dressing, croutons, and parmesan cheese.",
    price: 8.99,
    rating: 4.3,
    image: "https://via.placeholder.com/150?text=Caesar+Salad",
  },
  {
    id: 8,
    name: "Grilled Chicken Sandwich",
    category: "Lunch",
    detail: "Grilled chicken breast with lettuce, tomato, and mayo on a bun.",
    price: 9.99,
    rating: 4.5,
    image: "https://via.placeholder.com/150?text=Grilled+Chicken+Sandwich",
  },
  {
    id: 9,
    name: "Quinoa Salad",
    category: "Lunch",
    detail: "Quinoa mixed with cucumbers, tomatoes, and a lemon vinaigrette.",
    price: 7.99,
    rating: 4.2,
    image: "https://via.placeholder.com/150?text=Quinoa+Salad",
  },
  {
    id: 10,
    name: "Veggie Wrap",
    category: "Lunch",
    detail: "Whole wheat wrap filled with mixed vegetables and hummus.",
    price: 8.49,
    rating: 4.1,
    image: "https://via.placeholder.com/150?text=Veggie+Wrap",
  },
  {
    id: 11,
    name: "Club Sandwich",
    category: "Lunch",
    detail: "Triple-layer sandwich with turkey, bacon, lettuce, and tomato.",
    price: 10.99,
    rating: 4.6,
    image: "https://via.placeholder.com/150?text=Club+Sandwich",
  },
  {
    id: 12,
    name: "Margarita Pizza",
    category: "Lunch",
    detail: "Classic pizza with tomato, mozzarella, and fresh basil.",
    price: 11.99,
    rating: 4.7,
    image: "https://via.placeholder.com/150?text=Margarita+Pizza",
  },

  // Dinner items
  {
    id: 13,
    name: "Grilled Salmon",
    category: "Dinner",
    detail: "Grilled salmon fillet served with steamed vegetables.",
    price: 14.99,
    rating: 4.8,
    image: "https://via.placeholder.com/150?text=Grilled+Salmon",
  },
  {
    id: 14,
    name: "Steak",
    category: "Dinner",
    detail: "Juicy sirloin steak served with mashed potatoes and green beans.",
    price: 18.99,
    rating: 4.7,
    image: "https://via.placeholder.com/150?text=Steak",
  },
  {
    id: 15,
    name: "Pasta Primavera",
    category: "Dinner",
    detail: "Pasta tossed with a variety of fresh vegetables and olive oil.",
    price: 13.99,
    rating: 4.4,
    image: "https://via.placeholder.com/150?text=Pasta+Primavera",
  },
  {
    id: 16,
    name: "Chicken Alfredo",
    category: "Dinner",
    detail:
      "Creamy Alfredo sauce over fettuccine noodles with grilled chicken.",
    price: 15.99,
    rating: 4.6,
    image: "https://via.placeholder.com/150?text=Chicken+Alfredo",
  },
  {
    id: 17,
    name: "Vegetable Stir Fry",
    category: "Dinner",
    detail: "Mixed vegetables stir-fried with a savory sauce over rice.",
    price: 12.99,
    rating: 4.3,
    image: "https://via.placeholder.com/150?text=Vegetable+Stir+Fry",
  },
  {
    id: 18,
    name: "Beef Tacos",
    category: "Dinner",
    detail: "Soft tortillas filled with seasoned beef, lettuce, and cheese.",
    price: 9.99,
    rating: 4.5,
    image: "https://via.placeholder.com/150?text=Beef+Tacos",
  },

  // Starter items
  {
    id: 19,
    name: "Bruschetta",
    category: "Starter",
    detail: "Toasted bread topped with diced tomatoes, garlic, and basil.",
    price: 4.99,
    rating: 4.6,
    image: "https://via.placeholder.com/150?text=Bruschetta",
  },
  {
    id: 20,
    name: "Stuffed Mushrooms",
    category: "Starter",
    detail: "Mushroom caps stuffed with a blend of cheese and herbs.",
    price: 5.99,
    rating: 4.5,
    image: "https://via.placeholder.com/150?text=Stuffed+Mushrooms",
  },
  {
    id: 21,
    name: "Chicken Wings",
    category: "Starter",
    detail: "Spicy chicken wings served with blue cheese dipping sauce.",
    price: 6.99,
    rating: 4.7,
    image: "https://via.placeholder.com/150?text=Chicken+Wings",
  },
  {
    id: 22,
    name: "Mozzarella Sticks",
    category: "Starter",
    detail: "Fried mozzarella cheese sticks served with marinara sauce.",
    price: 5.49,
    rating: 4.4,
    image: "https://via.placeholder.com/150?text=Mozzarella+Sticks",
  },
  {
    id: 23,
    name: "Garlic Bread",
    category: "Starter",
    detail:
      "Bread topped with garlic butter and parsley, toasted to perfection.",
    price: 3.99,
    rating: 4.3,
    image: "https://via.placeholder.com/150?text=Garlic+Bread",
  },
  {
    id: 24,
    name: "Spring Rolls",
    category: "Starter",
    detail:
      "Crispy spring rolls filled with vegetables, served with dipping sauce.",
    price: 4.49,
    rating: 4.5,
    image: "https://via.placeholder.com/150?text=Spring+Rolls",
  },
];

export default foodItems;
